ifeq ($(origin CC),default)
CC := gcc
endif

ifeq ($(origin STRIP),undefined)
STRIP := strip
endif

BUILD_VERSION ?= $(shell date +%Y.%m.%d)

CFLAGS ?= -Os -ffunction-sections -fdata-sections -fno-pie
CPPFLAGS ?= -DBUILD_VERSION=\"$(BUILD_VERSION)\"
LDFLAGS ?= -static -no-pie -Wl,--gc-sections
LDLIBS ?= -lpthread

OBJS := adb-web.o

all: clean adb-web

webpage.h: index.html
	@echo "// Auto-generated by xxd" > $@
	@echo "static const unsigned char webpage_html_data[] = {" >> $@
	@xxd -i < index.html >> $@
	@echo ", 0x00};" >> $@
	@echo "static const char *webpage_html = (const char *)webpage_html_data;" >> $@

%.o: %.c webpage.h
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

adb-web: $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $@ $(LDLIBS)
	$(STRIP) $@

clean:
	rm -f adb-web *.o webpage.h

.PHONY: all clean
